print("Pirmas kartas")
print('Antras kartas')
print("I'm a programmer")
print("I'm the \"best\" programmer")
print('I\'m the "best" programmer')

# Tekstas vienoje eiluteje
print("Tekstas", end=' | ')
print("vienoje", end=' | ')
print("eiluteje", end=' | ')
print("Kitas printas")
print("tekstas \n keliuose \n eilutese")
print("c:\\User\\Data\\new.txt")
print("Pirmas", "Antras")
print("Pirmas"+"Antras")
